// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ad_events.proto

package adevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType defines the types of ad events
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_IMPRESSION  EventType = 1 // Ad was displayed
	EventType_EVENT_TYPE_CLICK       EventType = 2 // Ad was clicked
	EventType_EVENT_TYPE_VIEW        EventType = 3 // Ad was viewed (e.g., video ad played)
	EventType_EVENT_TYPE_CONVERSION  EventType = 4 // User performed desired action
	EventType_EVENT_TYPE_SKIP        EventType = 5 // Ad was skipped
	EventType_EVENT_TYPE_COMPLETE    EventType = 6 // Ad was completed (full duration)
	EventType_EVENT_TYPE_ERROR       EventType = 7 // Error occurred during ad delivery
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_IMPRESSION",
		2: "EVENT_TYPE_CLICK",
		3: "EVENT_TYPE_VIEW",
		4: "EVENT_TYPE_CONVERSION",
		5: "EVENT_TYPE_SKIP",
		6: "EVENT_TYPE_COMPLETE",
		7: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_IMPRESSION":  1,
		"EVENT_TYPE_CLICK":       2,
		"EVENT_TYPE_VIEW":        3,
		"EVENT_TYPE_CONVERSION":  4,
		"EVENT_TYPE_SKIP":        5,
		"EVENT_TYPE_COMPLETE":    6,
		"EVENT_TYPE_ERROR":       7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ad_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_ad_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{0}
}

// AdEvent represents a single ad event in the system
type AdEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Timestamp when the event occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// User who triggered the event
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Advertisement identifier
	AdId string `protobuf:"bytes,4,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	// Type of ad event
	EventType EventType `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=adevent.EventType" json:"event_type,omitempty"`
	// Additional metadata
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Session information
	SessionId string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Device information
	Device *DeviceInfo `protobuf:"bytes,8,opt,name=device,proto3" json:"device,omitempty"`
	// Geographic information
	GeoLocation   *GeoLocation `protobuf:"bytes,9,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdEvent) Reset() {
	*x = AdEvent{}
	mi := &file_proto_ad_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEvent) ProtoMessage() {}

func (x *AdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEvent.ProtoReflect.Descriptor instead.
func (*AdEvent) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{0}
}

func (x *AdEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AdEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AdEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdEvent) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *AdEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AdEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AdEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdEvent) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *AdEvent) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

// DeviceInfo contains device-specific information
type DeviceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceType      string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`                // mobile, desktop, tablet, tv
	OperatingSystem string                 `protobuf:"bytes,2,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"` // iOS, Android, Windows, etc.
	Browser         string                 `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`                                        // Chrome, Safari, Firefox, etc.
	UserAgent       string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                   // Full user agent string
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_ad_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceInfo) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *DeviceInfo) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *DeviceInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// GeoLocation contains geographic information
type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_proto_ad_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{2}
}

func (x *GeoLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoLocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Request message for sending ad events
type SendAdEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *AdEvent               `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAdEventRequest) Reset() {
	*x = SendAdEventRequest{}
	mi := &file_proto_ad_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAdEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAdEventRequest) ProtoMessage() {}

func (x *SendAdEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAdEventRequest.ProtoReflect.Descriptor instead.
func (*SendAdEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{3}
}

func (x *SendAdEventRequest) GetEvent() *AdEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// Response message for ad event submission
type SendAdEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAdEventResponse) Reset() {
	*x = SendAdEventResponse{}
	mi := &file_proto_ad_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAdEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAdEventResponse) ProtoMessage() {}

func (x *SendAdEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAdEventResponse.ProtoReflect.Descriptor instead.
func (*SendAdEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{4}
}

func (x *SendAdEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendAdEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendAdEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// Request for batch sending multiple ad events
type SendAdEventBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AdEvent             `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAdEventBatchRequest) Reset() {
	*x = SendAdEventBatchRequest{}
	mi := &file_proto_ad_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAdEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAdEventBatchRequest) ProtoMessage() {}

func (x *SendAdEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAdEventBatchRequest.ProtoReflect.Descriptor instead.
func (*SendAdEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{5}
}

func (x *SendAdEventBatchRequest) GetEvents() []*AdEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Response for batch ad event submission
type SendAdEventBatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	FailedEventIds []string               `protobuf:"bytes,4,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendAdEventBatchResponse) Reset() {
	*x = SendAdEventBatchResponse{}
	mi := &file_proto_ad_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAdEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAdEventBatchResponse) ProtoMessage() {}

func (x *SendAdEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAdEventBatchResponse.ProtoReflect.Descriptor instead.
func (*SendAdEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{6}
}

func (x *SendAdEventBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendAdEventBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendAdEventBatchResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *SendAdEventBatchResponse) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_ad_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{7}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_ad_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_events_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_ad_events_proto protoreflect.FileDescriptor

const file_proto_ad_events_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ad_events.proto\x12\aadevent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x03\n" +
	"\aAdEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x13\n" +
	"\x05ad_id\x18\x04 \x01(\tR\x04adId\x121\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x12.adevent.EventTypeR\teventType\x12:\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1e.adevent.AdEvent.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12+\n" +
	"\x06device\x18\b \x01(\v2\x13.adevent.DeviceInfoR\x06device\x127\n" +
	"\fgeo_location\x18\t \x01(\v2\x14.adevent.GeoLocationR\vgeoLocation\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12)\n" +
	"\x10operating_system\x18\x02 \x01(\tR\x0foperatingSystem\x12\x18\n" +
	"\abrowser\x18\x03 \x01(\tR\abrowser\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"\x8d\x01\n" +
	"\vGeoLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"<\n" +
	"\x12SendAdEventRequest\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.adevent.AdEventR\x05event\"d\n" +
	"\x13SendAdEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"C\n" +
	"\x17SendAdEventBatchRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.adevent.AdEventR\x06events\"\xa1\x01\n" +
	"\x18SendAdEventBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x05R\x0eprocessedCount\x12(\n" +
	"\x10failed_event_ids\x18\x04 \x03(\tR\x0efailedEventIds\"\x14\n" +
	"\x12HealthCheckRequest\"\xc8\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12C\n" +
	"\adetails\x18\x03 \x03(\v2).adevent.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xcc\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_IMPRESSION\x10\x01\x12\x14\n" +
	"\x10EVENT_TYPE_CLICK\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_VIEW\x10\x03\x12\x19\n" +
	"\x15EVENT_TYPE_CONVERSION\x10\x04\x12\x13\n" +
	"\x0fEVENT_TYPE_SKIP\x10\x05\x12\x17\n" +
	"\x13EVENT_TYPE_COMPLETE\x10\x06\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\a2\xfd\x01\n" +
	"\x0eAdEventService\x12H\n" +
	"\vSendAdEvent\x12\x1b.adevent.SendAdEventRequest\x1a\x1c.adevent.SendAdEventResponse\x12W\n" +
	"\x10SendAdEventBatch\x12 .adevent.SendAdEventBatchRequest\x1a!.adevent.SendAdEventBatchResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.adevent.HealthCheckRequest\x1a\x1c.adevent.HealthCheckResponseB\"Z ad-event-processor/proto/adeventb\x06proto3"

var (
	file_proto_ad_events_proto_rawDescOnce sync.Once
	file_proto_ad_events_proto_rawDescData []byte
)

func file_proto_ad_events_proto_rawDescGZIP() []byte {
	file_proto_ad_events_proto_rawDescOnce.Do(func() {
		file_proto_ad_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ad_events_proto_rawDesc), len(file_proto_ad_events_proto_rawDesc)))
	})
	return file_proto_ad_events_proto_rawDescData
}

var file_proto_ad_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ad_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ad_events_proto_goTypes = []any{
	(EventType)(0),                   // 0: adevent.EventType
	(*AdEvent)(nil),                  // 1: adevent.AdEvent
	(*DeviceInfo)(nil),               // 2: adevent.DeviceInfo
	(*GeoLocation)(nil),              // 3: adevent.GeoLocation
	(*SendAdEventRequest)(nil),       // 4: adevent.SendAdEventRequest
	(*SendAdEventResponse)(nil),      // 5: adevent.SendAdEventResponse
	(*SendAdEventBatchRequest)(nil),  // 6: adevent.SendAdEventBatchRequest
	(*SendAdEventBatchResponse)(nil), // 7: adevent.SendAdEventBatchResponse
	(*HealthCheckRequest)(nil),       // 8: adevent.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 9: adevent.HealthCheckResponse
	nil,                              // 10: adevent.AdEvent.MetadataEntry
	nil,                              // 11: adevent.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_proto_ad_events_proto_depIdxs = []int32{
	12, // 0: adevent.AdEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: adevent.AdEvent.event_type:type_name -> adevent.EventType
	10, // 2: adevent.AdEvent.metadata:type_name -> adevent.AdEvent.MetadataEntry
	2,  // 3: adevent.AdEvent.device:type_name -> adevent.DeviceInfo
	3,  // 4: adevent.AdEvent.geo_location:type_name -> adevent.GeoLocation
	1,  // 5: adevent.SendAdEventRequest.event:type_name -> adevent.AdEvent
	1,  // 6: adevent.SendAdEventBatchRequest.events:type_name -> adevent.AdEvent
	11, // 7: adevent.HealthCheckResponse.details:type_name -> adevent.HealthCheckResponse.DetailsEntry
	4,  // 8: adevent.AdEventService.SendAdEvent:input_type -> adevent.SendAdEventRequest
	6,  // 9: adevent.AdEventService.SendAdEventBatch:input_type -> adevent.SendAdEventBatchRequest
	8,  // 10: adevent.AdEventService.HealthCheck:input_type -> adevent.HealthCheckRequest
	5,  // 11: adevent.AdEventService.SendAdEvent:output_type -> adevent.SendAdEventResponse
	7,  // 12: adevent.AdEventService.SendAdEventBatch:output_type -> adevent.SendAdEventBatchResponse
	9,  // 13: adevent.AdEventService.HealthCheck:output_type -> adevent.HealthCheckResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ad_events_proto_init() }
func file_proto_ad_events_proto_init() {
	if File_proto_ad_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ad_events_proto_rawDesc), len(file_proto_ad_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ad_events_proto_goTypes,
		DependencyIndexes: file_proto_ad_events_proto_depIdxs,
		EnumInfos:         file_proto_ad_events_proto_enumTypes,
		MessageInfos:      file_proto_ad_events_proto_msgTypes,
	}.Build()
	File_proto_ad_events_proto = out.File
	file_proto_ad_events_proto_goTypes = nil
	file_proto_ad_events_proto_depIdxs = nil
}
